schema = 1
default_transfer_time = 420
default_dwell_time = 30

[stations]
BP1 = "Choa Chu Kang" # NEW
BP2 = "South View" # NEW
BP3 = "Keat Hong" # NEW
BP4 = "Teck Whye" # NEW
BP5 = "Phoenix" # NEW
BP6 = "Bukit Panjang" # NEW
BP7 = "Petir" # NEW
BP8 = "Pending" # NEW
BP9 = "Bangkit" # NEW
BP10 = "Fajar" # NEW
BP11 = "Segar" # NEW
BP12 = "Jelapang" # NEW
BP13 = "Senja" # NEW
BP14 = "Ten Mile Junction" # NEW
CG = "Tanah Merah" # NEW
CG1 = "Expo" # NEW
EW1 = "Pasir Ris" # NEW
EW2 = "Tampines" # NEW
EW3 = "Simei" # NEW
EW4 = "Tanah Merah" # NEW
EW5 = "Bedok" # NEW
EW6 = "Kembangan" # NEW
EW7 = "Eunos" # NEW
EW8 = "Paya Lebar" # NEW
EW9 = "Aljunied" # NEW
EW10 = "Kallang" # NEW
EW11 = "Lavender" # NEW
EW12 = "Bugis" # NEW
EW13 = "City Hall" # NEW
EW14 = "Raffles Place" # NEW
EW15 = "Tanjong Pagar" # NEW
EW16 = "Outram Park" # NEW
EW17 = "Tiong Bahru" # NEW
EW18 = "Redhill" # NEW
EW19 = "Queenstown" # NEW
EW20 = "Commonwealth" # NEW
EW21 = "Buona Vista" # NEW
EW23 = "Clementi" # NEW
EW24 = "Jurong East" # NEW
EW25 = "Chinese Garden" # NEW
EW26 = "Lakeside" # NEW
EW27 = "Boon Lay" # NEW
NS1 = "Jurong East" # NEW
NS2 = "Bukit Batok" # NEW
NS3 = "Bukit Gombak" # NEW
NS4 = "Choa Chu Kang" # NEW
NS5 = "Yew Tee" # NEW
NS7 = "Kranji" # NEW
NS8 = "Marsiling" # NEW
NS9 = "Woodlands" # NEW
NS10 = "Admiralty" # NEW
NS11 = "Sembawang" # NEW
NS13 = "Yishun" # NEW
NS14 = "Khatib" # NEW
NS15 = "Yio Chu Kang" # NEW
NS16 = "Ang Mo Kio" # NEW
NS17 = "Bishan" # NEW
NS18 = "Braddell" # NEW
NS19 = "Toa Payoh" # NEW
NS20 = "Novena" # NEW
NS21 = "Newton" # NEW
NS22 = "Orchard" # NEW
NS23 = "Somerset" # NEW
NS24 = "Dhoby Ghaut" # NEW
NS25 = "City Hall" # NEW
NS26 = "Raffles Place" # NEW
NS27 = "Marina Bay" # NEW

[segments]
BP1-BP2 = {duration = 120} # NEW
BP2-BP3 = {duration = 60} # NEW
BP3-BP4 = {duration = 120} # NEW
BP4-BP5 = {duration = 60} # NEW
BP5-BP6 = {duration = 60, edge_type = "bukit_panjang_main"} # NEW
BP6-BP7 = {duration = 60, edge_type = "bukit_panjang_service_b"} # NEW
BP6-BP13 = {duration = 120, edge_type = "bukit_panjang_service_a"} # NEW
BP6-BP14 = {duration = 60, edge_type = "bukit_panjang_service_c"} # NEW
BP7-BP8 = {duration = 120} # NEW
BP8-BP9 = {duration = 60} # NEW
BP9-BP10 = {duration = 120} # NEW
BP10-BP11 = {duration = 60} # NEW
BP11-BP12 = {duration = 60} # NEW
BP12-BP13 = {duration = 120} # NEW
CG-CG1 = {duration = 180} # NEW
EW1-EW2 = {duration = 180} # NEW
EW2-EW3 = {duration = 180} # NEW
EW3-EW4 = {duration = 180} # NEW
EW4-EW5 = {duration = 180} # NEW
EW5-EW6 = {duration = 180} # NEW
EW6-EW7 = {duration = 180} # NEW
EW7-EW8 = {duration = 120} # NEW
EW8-EW9 = {duration = 120} # NEW
EW9-EW10 = {duration = 180} # NEW
EW10-EW11 = {duration = 120} # NEW
EW11-EW12 = {duration = 180} # NEW
EW12-EW13 = {duration = 120} # NEW
EW13-EW14 = {duration = 120} # NEW
EW14-EW15 = {duration = 120} # NEW
EW15-EW16 = {duration = 120} # NEW
EW16-EW17 = {duration = 180} # NEW
EW17-EW18 = {duration = 180} # NEW
EW18-EW19 = {duration = 120} # NEW
EW19-EW20 = {duration = 180} # NEW
EW20-EW21 = {duration = 120} # NEW
EW21-EW23 = {duration = 300} # NEW
EW23-EW24 = {duration = 300} # NEW
EW24-EW25 = {duration = 120} # NEW
EW25-EW26 = {duration = 180} # NEW
EW26-EW27 = {duration = 120} # NEW
NS1-NS2 = {duration = 180} # NEW
NS2-NS3 = {duration = 180} # NEW
NS3-NS4 = {duration = 240} # NEW
NS4-NS5 = {duration = 120} # NEW
NS5-NS7 = {duration = 300} # NEW
NS7-NS8 = {duration = 180} # NEW
NS8-NS9 = {duration = 180} # NEW
NS9-NS10 = {duration = 180} # NEW
NS10-NS11 = {duration = 180} # NEW
NS11-NS13 = {duration = 300} # NEW
NS13-NS14 = {duration = 120} # NEW
NS14-NS15 = {duration = 300} # NEW
NS15-NS16 = {duration = 180} # NEW
NS16-NS17 = {duration = 240} # NEW
NS17-NS18 = {duration = 120} # NEW
NS18-NS19 = {duration = 120} # NEW
NS19-NS20 = {duration = 180} # NEW
NS20-NS21 = {duration = 120} # NEW
NS21-NS22 = {duration = 180} # NEW
NS22-NS23 = {duration = 120} # NEW
NS23-NS24 = {duration = 120} # NEW
NS24-NS25 = {duration = 180} # NEW
NS25-NS26 = {duration = 120} # NEW
NS26-NS27 = {duration = 120} # NEW

[transfers]
BP1-NS4 = {duration = 420} # NEW
CG-EW4 = {duration = 420} # NEW
EW4-CG = {duration = 420} # NEW
EW13-NS25 = {duration = 360} # NEW
EW14-NS26 = {duration = 360} # NEW
EW24-NS1 = {duration = 420} # NEW
NS1-EW24 = {duration = 420} # NEW
NS4-BP1 = {duration = 420} # NEW
NS25-EW13 = {duration = 360} # NEW
NS26-EW14 = {duration = 360} # NEW
