schema = 1
default_transfer_time = 420
default_dwell_time = 30

[stations]
BP1 = "Choa Chu Kang"
BP2 = "South View"
BP3 = "Keat Hong"
BP4 = "Teck Whye"
BP5 = "Phoenix"
BP6 = "Bukit Panjang"
BP7 = "Petir"
BP8 = "Pending"
BP9 = "Bangkit"
BP10 = "Fajar"
BP11 = "Segar"
BP12 = "Jelapang"
BP13 = "Senja"
CC1 = "Dhoby Ghaut"
CC2 = "Bras Basah"
CC3 = "Esplanade"
CC4 = "Promenade"
CC5 = "Nicoll Highway"
CC6 = "Stadium"
CC7 = "Mountbatten"
CC8 = "Dakota"
CC9 = "Paya Lebar"
CC10 = "MacPherson"
CC11 = "Tai Seng"
CC12 = "Bartley"
CC13 = "Serangoon"
CC14 = "Lorong Chuan"
CC15 = "Bishan"
CC16 = "Marymount"
CC17 = "Caldecott"
CC19 = "Botanic Gardens"
CC20 = "Farrer Road"
CC21 = "Holland Village"
CC22 = "Buona Vista"
CC23 = "one-north"
CC24 = "Kent Ridge"
CC25 = "Haw Par Villa"
CC26 = "Pasir Panjang"
CC27 = "Labrador Park"
CC28 = "Telok Blangah"
CC29 = "HarbourFront"
CC30 = "Keppel"
CC31 = "Cantonment"
CC32 = "Prince Edward Road"
CC33 = "Marina Bay"
CC34 = "Bayfront"
CG = "Tanah Merah"
CG1 = "Expo"
CG2 = "Changi Airport"
DT1 = "Bukit Panjang"
DT2 = "Cashew"
DT3 = "Hillview"
DT4 = "Hume"
DT5 = "Beauty World"
DT6 = "King Albert Park"
DT7 = "Sixth Avenue"
DT8 = "Tan Kah Kee"
DT9 = "Botanic Gardens"
DT10 = "Stevens"
DT11 = "Newton"
DT12 = "Little India"
DT13 = "Rochor"
DT14 = "Bugis"
DT15 = "Promenade"
DT16 = "Bayfront"
DT17 = "Downtown"
DT18 = "Telok Ayer"
DT19 = "Chinatown"
DT20 = "Fort Canning"
DT21 = "Bencoolen"
DT22 = "Jalan Besar"
DT23 = "Bendemeer"
DT24 = "Geylang Bahru"
DT25 = "Mattar"
DT26 = "MacPherson"
DT27 = "Ubi"
DT28 = "Kaki Bukit"
DT29 = "Bedok North"
DT30 = "Bedok Reservoir"
DT31 = "Tampines West"
DT32 = "Tampines"
DT33 = "Tampines East"
DT34 = "Upper Changi"
DT35 = "Expo"
DT36 = "Xilin"
DT37 = "Sungei Bedok"
EW1 = "Pasir Ris"
EW2 = "Tampines"
EW3 = "Simei"
EW4 = "Tanah Merah"
EW5 = "Bedok"
EW6 = "Kembangan"
EW7 = "Eunos"
EW8 = "Paya Lebar"
EW9 = "Aljunied"
EW10 = "Kallang"
EW11 = "Lavender"
EW12 = "Bugis"
EW13 = "City Hall"
EW14 = "Raffles Place"
EW15 = "Tanjong Pagar"
EW16 = "Outram Park"
EW17 = "Tiong Bahru"
EW18 = "Redhill"
EW19 = "Queenstown"
EW20 = "Commonwealth"
EW21 = "Buona Vista"
EW22 = "Dover"
EW23 = "Clementi"
EW24 = "Jurong East"
EW25 = "Chinese Garden"
EW26 = "Lakeside"
EW27 = "Boon Lay"
EW28 = "Pioneer"
EW29 = "Joo Koon"
EW30 = "Gul Circle"
EW31 = "Tuas Crescent"
EW32 = "Tuas West Road"
EW33 = "Tuas Link"
JE0 = "Tengah"
JE1 = "Tengah Plantation"
JE2 = "Tengah Park"
JE3 = "Bukit Batok West"
JE4 = "Toh Guan"
JE5 = "Jurong East"
JE6 = "Jurong Town Hall"
JE7 = "Pandan Reservoir"
JS1 = "Choa Chu Kang"
JS2 = "Choa Chu Kang West"
JS3 = "Tengah"
JS4 = "Hong Kah"
JS5 = "Corporation"
JS6 = "Jurong West"
JS7 = "Bahar Junction"
JS8 = "Boon Lay"
JS9 = "Enterprise"
JS10 = "Tukang"
JS11 = "Jurong Hill"
JS12 = "Jurong Pier"
JW1 = "Gek Poh"
JW2 = "Tawas"
JW3 = "Nanyang Gateway"
JW4 = "Nanyang Crescent"
JW5 = "Peng Kang Hill"
NE1 = "HarbourFront"
NE3 = "Outram Park"
NE4 = "Chinatown"
NE5 = "Clarke Quay"
NE6 = "Dhoby Ghaut"
NE7 = "Little India"
NE8 = "Farrer Park"
NE9 = "Boon Keng"
NE10 = "Potong Pasir"
NE11 = "Woodleigh"
NE12 = "Serangoon"
NE13 = "Kovan"
NE14 = "Hougang"
NE15 = "Buangkok"
NE16 = "Sengkang"
NE17 = "Punggol"
NE18 = "Punggol Coast"
NS1 = "Jurong East"
NS2 = "Bukit Batok"
NS3 = "Bukit Gombak"
NS4 = "Choa Chu Kang"
NS5 = "Yew Tee"
NS7 = "Kranji"
NS8 = "Marsiling"
NS9 = "Woodlands"
NS10 = "Admiralty"
NS11 = "Sembawang"
NS12 = "Canberra"
NS13 = "Yishun"
NS14 = "Khatib"
NS15 = "Yio Chu Kang"
NS16 = "Ang Mo Kio"
NS17 = "Bishan"
NS18 = "Braddell"
NS19 = "Toa Payoh"
NS20 = "Novena"
NS21 = "Newton"
NS22 = "Orchard"
NS23 = "Somerset"
NS24 = "Dhoby Ghaut"
NS25 = "City Hall"
NS26 = "Raffles Place"
NS27 = "Marina Bay"
NS28 = "Marina South Pier"
PE1 = "Cove"
PE2 = "Meridian"
PE3 = "Coral Edge"
PE4 = "Riviera"
PE5 = "Kadaloor"
PE6 = "Oasis"
PE7 = "Damai"
PTC = "Punggol"
PW1 = "Sam Kee"
PW2 = "Teck Lee"
PW3 = "Punggol Point"
PW4 = "Samudera"
PW5 = "Nibong"
PW6 = "Sumang"
PW7 = "Soo Teck"
SE1 = "Compassvale"
SE2 = "Rumbia"
SE3 = "Bakau"
SE4 = "Kangkar"
SE5 = "Ranggung"
STC = "Sengkang"
SW1 = "Cheng Lim"
SW2 = "Farmway"
SW3 = "Kupang"
SW4 = "Thanggam"
SW5 = "Fernvale"
SW6 = "Layar"
SW7 = "Tongkang"
SW8 = "Renjong"
TE1 = "Woodlands North"
TE2 = "Woodlands"
TE3 = "Woodlands South"
TE4 = "Springleaf"
TE5 = "Lentor"
TE6 = "Mayflower"
TE7 = "Bright Hill"
TE8 = "Upper Thomson"
TE9 = "Caldecott"
TE11 = "Stevens"
TE12 = "Napier"
TE13 = "Orchard Boulevard"
TE14 = "Orchard"
TE15 = "Great World"
TE16 = "Havelock"
TE17 = "Outram Park"
TE18 = "Maxwell"
TE19 = "Shenton Way"
TE20 = "Marina Bay"
TE22 = "Gardens by the Bay"
TE22A = "Founders' Memorial"
TE23 = "Tanjong Rhu"
TE24 = "Katong Park"
TE25 = "Tanjong Katong"
TE26 = "Marine Parade"
TE27 = "Marine Terrace"
TE28 = "Siglap"
TE29 = "Bayshore"
TE30 = "Bedok South"
TE31 = "Sungei Bedok"

[segments]
BP1-BP2 = {duration = 120}
BP2-BP3 = {duration = 60}
BP3-BP4 = {duration = 120}
BP4-BP5 = {duration = 60}
BP5-BP6 = {duration = 60, edge_type = "bukit_panjang_main"}
BP6-BP7 = {duration = 60, edge_type = "bukit_panjang_service_b"}
BP6-BP13 = {duration = 120, edge_type = "bukit_panjang_service_a"}
BP7-BP8 = {duration = 120}
BP8-BP9 = {duration = 60}
BP9-BP10 = {duration = 120}
BP10-BP11 = {duration = 60}
BP11-BP12 = {duration = 60}
BP12-BP13 = {duration = 120}
CC1-CC2 = {duration = 180}
CC1-DT21 = {duration = 300, mode = "walk"}
CC2-CC3 = {duration = 180}
CC2-DT14 = {duration = 600, mode = "walk"}
CC2-DT21 = {duration = 120, mode = "walk"}
CC2-EW12 = {duration = 600, mode = "walk"}
CC2-EW13 = {duration = 420, mode = "walk"}
CC2-NS25 = {duration = 420, mode = "walk"}
CC3-CC4 = {duration = 180, edge_type = "promenade_west"}
CC3-DT14 = {duration = 720, mode = "walk"}
CC3-EW12 = {duration = 720, mode = "walk"}
CC3-EW13 = {duration = 300, mode = "walk"}
CC3-NS25 = {duration = 300, mode = "walk"}
CC4-CC5 = {duration = 360, edge_type = "promenade_east"}
CC4-CC34 = {duration = 180, edge_type = "promenade_south"}
CC5-CC6 = {duration = 120}
CC6-CC7 = {duration = 120}
CC7-CC8 = {duration = 120}
CC8-CC9 = {duration = 120}
CC9-CC10 = {duration = 120}
CC10-CC11 = {duration = 120}
CC11-CC12 = {duration = 120}
CC12-CC13 = {duration = 120}
CC13-CC14 = {duration = 120}
CC14-CC15 = {duration = 120}
CC15-CC16 = {duration = 120}
CC16-CC17 = {duration = 120}
CC17-CC19 = {duration = 300}
CC19-CC20 = {duration = 120}
CC20-CC21 = {duration = 120}
CC21-CC22 = {duration = 120}
CC22-CC23 = {duration = 120}
CC23-CC24 = {duration = 120}
CC24-CC25 = {duration = 120}
CC25-CC26 = {duration = 120} # NEW
CC26-CC27 = {duration = 120} # NEW
CC27-CC28 = {duration = 120} # NEW
CC28-CC29 = {duration = 120} # NEW
CC29-CC30 = {duration = 120} # NEW
CC30-CC31 = {duration = 60} # NEW
CC31-CC32 = {duration = 60} # NEW
CC32-CC33 = {duration = 60} # NEW
CC33-CC34 = {duration = 120} # NEW
CC33-DT17 = {duration = 300, mode = "walk"} # NEW
CG-CG1 = {duration = 180} # NEW
CG1-CG2 = {duration = 240} # NEW
DT1-DT2 = {duration = 120} # NEW
DT2-DT3 = {duration = 120} # NEW
DT3-DT4 = {duration = 120} # NEW
DT4-DT5 = {duration = 180} # NEW
DT5-DT6 = {duration = 120} # NEW
DT6-DT7 = {duration = 120} # NEW
DT7-DT8 = {duration = 120} # NEW
DT8-DT9 = {duration = 120} # NEW
DT9-DT10 = {duration = 120} # NEW
DT10-DT11 = {duration = 120} # NEW
DT11-DT12 = {duration = 180} # NEW
DT12-DT13 = {duration = 60} # NEW
DT12-DT22 = {duration = 600, mode = "walk"} # NEW
DT13-DT14 = {duration = 120} # NEW
DT13-DT21 = {duration = 540, mode = "walk"} # NEW
DT13-DT22 = {duration = 300, mode = "walk"} # NEW
DT14-DT15 = {duration = 120} # NEW
DT15-DT16 = {duration = 120} # NEW
DT16-DT17 = {duration = 120} # NEW
DT17-DT18 = {duration = 60} # NEW
DT17-EW14 = {duration = 420, mode = "walk"} # NEW
DT17-NS26 = {duration = 420, mode = "walk"} # NEW
DT18-DT19 = {duration = 120} # NEW
DT18-EW14 = {duration = 300, mode = "walk"} # NEW
DT18-EW15 = {duration = 480, mode = "walk"} # NEW
DT18-NS26 = {duration = 300, mode = "walk"} # NEW
DT19-DT20 = {duration = 120} # NEW
DT19-EW14 = {duration = 660, mode = "walk"} # NEW
DT19-NS26 = {duration = 660, mode = "walk"} # NEW
DT19-TE18 = {duration = 600, mode = "walk"} # NEW
DT20-DT21 = {duration = 120} # NEW
DT20-NE5 = {duration = 600, mode = "walk"} # NEW
DT21-DT22 = {duration = 60} # NEW
DT22-DT14 = {duration = 540, mode = "walk"} # NEW
DT22-DT23 = {duration = 120} # NEW
DT22-EW12 = {duration = 540, mode = "walk"} # NEW
DT23-DT24 = {duration = 120} # NEW
DT24-DT25 = {duration = 120} # NEW
DT25-DT26 = {duration = 120} # NEW
DT26-DT27 = {duration = 120} # NEW
DT27-DT28 = {duration = 120} # NEW
DT28-DT29 = {duration = 120} # NEW
DT29-DT30 = {duration = 120} # NEW
DT30-DT31 = {duration = 180} # NEW
DT31-DT32 = {duration = 120} # NEW
DT32-DT33 = {duration = 120} # NEW
DT33-DT34 = {duration = 180} # NEW
DT34-DT35 = {duration = 120} # NEW
DT35-DT36 = {duration = 60} # NEW
DT36-DT37 = {duration = 120} # NEW
EW1-EW2 = {duration = 180} # NEW
EW2-EW3 = {duration = 180} # NEW
EW3-EW4 = {duration = 180} # NEW
EW4-EW5 = {duration = 180} # NEW
EW5-EW6 = {duration = 180} # NEW
EW6-EW7 = {duration = 180} # NEW
EW7-EW8 = {duration = 120} # NEW
EW8-EW9 = {duration = 120} # NEW
EW9-EW10 = {duration = 180} # NEW
EW10-EW11 = {duration = 120} # NEW
EW11-EW12 = {duration = 180} # NEW
EW12-EW13 = {duration = 120} # NEW
EW13-EW14 = {duration = 120} # NEW
EW14-EW15 = {duration = 120} # NEW
EW15-EW16 = {duration = 120} # NEW
EW16-EW17 = {duration = 180} # NEW
EW17-EW18 = {duration = 180} # NEW
EW18-EW19 = {duration = 120} # NEW
EW19-EW20 = {duration = 180} # NEW
EW20-EW21 = {duration = 120} # NEW
EW21-EW22 = {duration = 180} # NEW
EW22-EW23 = {duration = 120} # NEW
EW23-EW24 = {duration = 300} # NEW
EW24-EW25 = {duration = 120} # NEW
EW25-EW26 = {duration = 180} # NEW
EW26-EW27 = {duration = 120} # NEW
EW27-EW28 = {duration = 180} # NEW
EW28-EW29 = {duration = 180} # NEW
EW29-EW30 = {duration = 240} # NEW
EW30-EW31 = {duration = 120} # NEW
EW31-EW32 = {duration = 120} # NEW
EW32-EW33 = {duration = 120} # NEW
JE0-JE1 = {duration = 180} # NEW
JE1-JE2 = {duration = 120} # NEW
JE2-JE3 = {duration = 120} # NEW
JE3-JE4 = {duration = 180} # NEW
JE4-JE5 = {duration = 120} # NEW
JE5-JE6 = {duration = 120} # NEW
JE6-JE7 = {duration = 120} # NEW
JS1-JS2 = {duration = 120} # NEW
JS2-JS3 = {duration = 240} # NEW
JS3-JS4 = {duration = 120} # NEW
JS4-JS5 = {duration = 180} # NEW
JS5-JS6 = {duration = 120} # NEW
JS6-JS7 = {duration = 120, edge_type = "bahar_east"} # NEW
JS7-JS8 = {duration = 120, edge_type = "bahar_south"} # NEW
JS7-JW1 = {duration = 120, edge_type = "bahar_west"} # NEW
JS8-JS9 = {duration = 120} # NEW
JS9-JS10 = {duration = 120} # NEW
JS10-JS11 = {duration = 120} # NEW
JS11-JS12 = {duration = 120} # NEW
JW1-JW2 = {duration = 120} # NEW
JW2-JW3 = {duration = 120} # NEW
JW3-JW4 = {duration = 120} # NEW
JW4-JW5 = {duration = 120} # NEW
NE1-NE3 = {duration = 240} # NEW
NE3-NE4 = {duration = 60} # NEW
NE4-EW14 = {duration = 660, mode = "walk"} # NEW
NE4-NE5 = {duration = 120} # NEW
NE4-NS26 = {duration = 660, mode = "walk"} # NEW
NE4-TE18 = {duration = 600, mode = "walk"} # NEW
NE5-EW14 = {duration = 600, mode = "walk"} # NEW
NE5-NE6 = {duration = 180} # NEW
NE5-NS26 = {duration = 600, mode = "walk"} # NEW
NE6-DT21 = {duration = 300, mode = "walk"} # NEW
NE6-NE7 = {duration = 60} # NEW
NE7-DT22 = {duration = 600, mode = "walk"} # NEW
NE7-NE8 = {duration = 60} # NEW
NE8-NE9 = {duration = 120} # NEW
NE9-DT23 = {duration = 600, mode = "walk"} # NEW
NE9-NE10 = {duration = 180} # NEW
NE10-NE11 = {duration = 60} # NEW
NE11-NE12 = {duration = 120} # NEW
NE12-NE13 = {duration = 180} # NEW
NE13-NE14 = {duration = 120} # NEW
NE14-NE15 = {duration = 120} # NEW
NE15-NE16 = {duration = 120} # NEW
NE16-NE17 = {duration = 180} # NEW
NE17-NE18 = {duration = 180} # NEW
NS1-NS2 = {duration = 180} # NEW
NS2-NS3 = {duration = 180} # NEW
NS3-NS4 = {duration = 240} # NEW
NS4-NS5 = {duration = 120} # NEW
NS5-NS7 = {duration = 300} # NEW
NS7-NS8 = {duration = 180} # NEW
NS8-NS9 = {duration = 180} # NEW
NS9-NS10 = {duration = 180} # NEW
NS10-NS11 = {duration = 180} # NEW
NS11-NS12 = {duration = 180} # NEW
NS12-NS13 = {duration = 180} # NEW
NS13-NS14 = {duration = 120} # NEW
NS14-NS15 = {duration = 300} # NEW
NS15-NS16 = {duration = 180} # NEW
NS16-NS17 = {duration = 240} # NEW
NS17-NS18 = {duration = 120} # NEW
NS18-NS19 = {duration = 120} # NEW
NS19-NS20 = {duration = 180} # NEW
NS20-NS21 = {duration = 120} # NEW
NS21-NS22 = {duration = 180} # NEW
NS22-NS23 = {duration = 120} # NEW
NS23-NS24 = {duration = 120} # NEW
NS24-DT21 = {duration = 300, mode = "walk"} # NEW
NS24-NS25 = {duration = 180} # NEW
NS25-NS26 = {duration = 120} # NEW
NS26-NS27 = {duration = 120} # NEW
NS27-DT17 = {duration = 300, mode = "walk"} # NEW
NS27-NS28 = {duration = 120} # NEW
PE1-PE2 = {duration = 60} # NEW
PE2-PE3 = {duration = 60} # NEW
PE3-PE4 = {duration = 60} # NEW
PE4-PE5 = {duration = 60} # NEW
PE5-PE6 = {duration = 60} # NEW
PE6-PE7 = {duration = 60} # NEW
PTC-PE1 = {duration = 180, edge_type = "punggol_east_loop"} # NEW
PTC-PE7 = {duration = 120, edge_type = "punggol_east_loop"} # NEW
PTC-PW1 = {duration = 120, edge_type = "punggol_west_loop"} # NEW
PTC-PW7 = {duration = 180, edge_type = "punggol_west_loop"} # NEW
PW1-PW2 = {duration = 60} # NEW
PW2-PW3 = {duration = 60} # NEW
PW3-PW4 = {duration = 60} # NEW
PW4-PW5 = {duration = 60} # NEW
PW5-PW6 = {duration = 60} # NEW
PW6-PW7 = {duration = 60} # NEW
SE1-SE2 = {duration = 60} # NEW
SE2-SE3 = {duration = 60} # NEW
SE3-SE4 = {duration = 60} # NEW
SE4-SE5 = {duration = 120} # NEW
STC-SE1 = {duration = 120, edge_type = "sengkang_east_loop"} # NEW
STC-SE5 = {duration = 180, edge_type = "sengkang_east_loop"} # NEW
STC-SW1 = {duration = 120, edge_type = "sengkang_west_loop"} # NEW
STC-SW8 = {duration = 180, edge_type = "sengkang_west_loop"} # NEW
SW1-SW2 = {duration = 60} # NEW
SW2-SW3 = {duration = 60} # NEW
SW3-SW4 = {duration = 60} # NEW
SW4-SW5 = {duration = 60} # NEW
SW5-SW6 = {duration = 60} # NEW
SW6-SW7 = {duration = 60} # NEW
SW7-SW8 = {duration = 60} # NEW
TE1-TE2 = {duration = 120} # NEW
TE2-TE3 = {duration = 120} # NEW
TE3-TE4 = {duration = 300} # NEW
TE4-TE5 = {duration = 180} # NEW
TE5-TE6 = {duration = 180} # NEW
TE6-TE7 = {duration = 120} # NEW
TE7-TE8 = {duration = 120} # NEW
TE8-TE9 = {duration = 180} # NEW
TE9-TE11 = {duration = 240} # NEW
TE11-TE12 = {duration = 180} # NEW
TE12-TE13 = {duration = 60} # NEW
TE13-TE14 = {duration = 120} # NEW
TE14-TE15 = {duration = 120} # NEW
TE15-TE16 = {duration = 120} # NEW
TE16-TE17 = {duration = 120} # NEW
TE17-TE18 = {duration = 120} # NEW
TE18-DT18 = {duration = 660, mode = "walk"} # NEW
TE18-EW15 = {duration = 480, mode = "walk"} # NEW
TE18-TE19 = {duration = 60} # NEW
TE19-DT17 = {duration = 360, mode = "walk"} # NEW
TE19-EW14 = {duration = 720, mode = "walk"} # NEW
TE19-EW15 = {duration = 600, mode = "walk"} # NEW
TE19-NS26 = {duration = 720, mode = "walk"} # NEW
TE19-TE20 = {duration = 120} # NEW
TE20-DT17 = {duration = 300, mode = "walk"} # NEW
TE20-TE22 = {duration = 180} # NEW
TE22-TE22A = {duration = 120} # NEW
TE22A-TE23 = {duration = 120} # NEW
TE23-TE24 = {duration = 120} # NEW
TE24-TE25 = {duration = 180} # NEW
TE25-TE26 = {duration = 60} # NEW
TE26-TE27 = {duration = 120} # NEW
TE27-TE28 = {duration = 120} # NEW
TE28-TE29 = {duration = 120} # NEW
TE29-TE30 = {duration = 60} # NEW
TE30-TE31 = {duration = 60} # NEW

[transfers]
BP1-JS1 = {duration = 420} # NEW
BP1-NS4 = {duration = 420} # NEW
BP6-DT1 = {duration = 600} # NEW
CC1-NE6 = {duration = 480} # NEW
CC1-NS24 = {duration = 480} # NEW
CC4-DT15 = {duration = 420} # NEW
CC9-EW8 = {duration = 480} # NEW
CC10-DT26 = {duration = 360} # NEW
CC13-NE12 = {duration = 480} # NEW
CC15-NS17 = {duration = 480} # NEW
CC17-TE9 = {duration = 540} # NEW
CC19-DT9 = {duration = 480} # NEW
CC22-EW21 = {duration = 480} # NEW
CC29-NE1 = {duration = 420} # NEW
CC33-NS27 = {duration = 600} # NEW
CC33-TE20 = {duration = 600} # NEW
CC34-DT16 = {duration = 360} # NEW
CG-EW4 = {duration = 420} # NEW
CG1-DT35 = {duration = 480} # NEW
DT1-BP6 = {duration = 600} # NEW
DT9-CC19 = {duration = 480} # NEW
DT10-TE11 = {duration = 420} # NEW
DT11-NS21 = {duration = 540} # NEW
DT12-NE7 = {duration = 480} # NEW
DT14-EW12 = {duration = 540} # NEW
DT15-CC4 = {duration = 420} # NEW
DT16-CC34 = {duration = 360} # NEW
DT19-NE4 = {duration = 420} # NEW
DT26-CC10 = {duration = 360} # NEW
DT32-EW2 = {duration = 720} # NEW
DT35-CG1 = {duration = 480} # NEW
DT37-TE31 = {duration = 540} # NEW
EW2-DT32 = {duration = 720} # NEW
EW4-CG = {duration = 420} # NEW
EW8-CC9 = {duration = 480} # NEW
EW12-DT14 = {duration = 540} # NEW
EW13-NS25 = {duration = 360} # NEW
EW14-NS26 = {duration = 360} # NEW
EW16-NE3 = {duration = 480} # NEW
EW16-TE17 = {duration = 480} # NEW
EW21-CC22 = {duration = 480} # NEW
EW24-JE5 = {duration = 420} # NEW
EW24-NS1 = {duration = 420} # NEW
EW27-JS8 = {duration = 600} # NEW
JE0-JS3 = {duration = 360} # NEW
JE5-EW24 = {duration = 420} # NEW
JE5-NS1 = {duration = 420} # NEW
JS1-BP1 = {duration = 420} # NEW
JS1-NS4 = {duration = 420} # NEW
JS3-JE0 = {duration = 360} # NEW
JS8-EW27 = {duration = 600} # NEW
NE1-CC29 = {duration = 420} # NEW
NE3-EW16 = {duration = 480} # NEW
NE3-TE17 = {duration = 480} # NEW
NE4-DT19 = {duration = 420} # NEW
NE6-CC1 = {duration = 480} # NEW
NE6-NS24 = {duration = 480} # NEW
NE7-DT12 = {duration = 480} # NEW
NE12-CC13 = {duration = 480} # NEW
NE16-STC = {duration = 420} # NEW
NE17-PTC = {duration = 420} # NEW
NS1-EW24 = {duration = 420} # NEW
NS1-JE5 = {duration = 420} # NEW
NS4-BP1 = {duration = 420} # NEW
NS4-JS1 = {duration = 420} # NEW
NS9-TE2 = {duration = 540} # NEW
NS17-CC15 = {duration = 480} # NEW
NS21-DT11 = {duration = 540} # NEW
NS22-TE14 = {duration = 480} # NEW
NS24-CC1 = {duration = 480} # NEW
NS24-NE6 = {duration = 480} # NEW
NS25-EW13 = {duration = 360} # NEW
NS26-EW14 = {duration = 360} # NEW
NS27-CC33 = {duration = 600} # NEW
NS27-TE20 = {duration = 600} # NEW
PTC-NE17 = {duration = 420} # NEW
STC-NE16 = {duration = 420} # NEW
TE2-NS9 = {duration = 540} # NEW
TE9-CC17 = {duration = 540} # NEW
TE11-DT10 = {duration = 420} # NEW
TE14-NS22 = {duration = 480} # NEW
TE17-EW16 = {duration = 480} # NEW
TE17-NE3 = {duration = 480} # NEW
TE20-CC33 = {duration = 600} # NEW
TE20-NS27 = {duration = 600} # NEW
TE31-DT37 = {duration = 540} # NEW
