schema = 1
default_transfer_time = 420
default_dwell_time = 30

[stations]
NS15 = "Yio Chu Kang"
NS16 = "Ang Mo Kio"
NS17 = "Bishan"
NS18 = "Braddell"
NS19 = "Toa Payoh"

[segments]
NS15-NS16 = {duration = 180}
NS16-NS17 = {duration = 240}
NS17-NS18 = {duration = 120}
NS18-NS19 = {duration = 120}

[transfers]
