schema = 1
default_transfer_time = 7
default_dwell_time_asc = 0.5
default_dwell_time_desc = 0.5

[stations]
BP1 = "Choa Chu Kang"
BP2 = "South View"
BP3 = "Keat Hong"
BP4 = "Teck Whye"
BP5 = "Phoenix"
BP6 = "Bukit Panjang"
BP7 = "Petir"
BP8 = "Pending"
BP9 = "Bangkit"
BP10 = "Fajar"
BP11 = "Segar"
BP12 = "Jelapang"
BP13 = "Senja"
BP14 = "Ten Mile Junction"
CC12 = "Bartley"
CC13 = "Serangoon"
CC14 = "Lorong Chuan"
CC15 = "Bishan"
CC16 = "Marymount"
CG = "Tanah Merah"
CG1 = "Expo"
CG2 = "Changi Airport"
EW1 = "Pasir Ris"
EW2 = "Tampines"
EW3 = "Simei"
EW4 = "Tanah Merah"
EW5 = "Bedok"
EW6 = "Kembangan"
EW7 = "Eunos"
EW8 = "Paya Lebar"
EW9 = "Aljunied"
EW10 = "Kallang"
EW11 = "Lavender"
EW12 = "Bugis"
EW13 = "City Hall"
EW14 = "Raffles Place"
EW15 = "Tanjong Pagar"
EW16 = "Outram Park"
EW17 = "Tiong Bahru"
EW18 = "Redhill"
EW19 = "Queenstown"
EW20 = "Commonwealth"
EW21 = "Buona Vista"
EW22 = "Dover"
EW23 = "Clementi"
EW24 = "Jurong East"
EW25 = "Chinese Garden"
EW26 = "Lakeside"
EW27 = "Boon Lay"
EW28 = "Pioneer"
EW29 = "Joo Koon"
NE1 = "HarbourFront"
NE3 = "Outram Park"
NE4 = "Chinatown"
NE5 = "Clarke Quay"
NE6 = "Dhoby Ghaut"
NE7 = "Little India"
NE8 = "Farrer Park"
NE9 = "Boon Keng"
NE10 = "Potong Pasir"
NE12 = "Serangoon"
NE13 = "Kovan"
NE14 = "Hougang"
NE15 = "Buangkok"
NE16 = "Sengkang"
NE17 = "Punggol"
NS1 = "Jurong East"
NS2 = "Bukit Batok"
NS3 = "Bukit Gombak"
NS4 = "Choa Chu Kang"
NS5 = "Yew Tee"
NS7 = "Kranji"
NS8 = "Marsiling"
NS9 = "Woodlands"
NS10 = "Admiralty"
NS11 = "Sembawang"
NS13 = "Yishun"
NS14 = "Khatib"
NS15 = "Yio Chu Kang"
NS16 = "Ang Mo Kio"
NS17 = "Bishan"
NS18 = "Braddell"
NS19 = "Toa Payoh"
NS20 = "Novena"
NS21 = "Newton"
NS22 = "Orchard"
NS23 = "Somerset"
NS24 = "Dhoby Ghaut"
NS25 = "City Hall"
NS26 = "Raffles Place"
NS27 = "Marina Bay"
PE1 = "Cove"
PE2 = "Meridian"
PE3 = "Coral Edge"
PE4 = "Riviera"
PE5 = "Kadaloor"
PE6 = "Oasis"
PTC = "Punggol"
SE1 = "Compassvale"
SE2 = "Rumbia"
SE3 = "Bakau"
SE4 = "Kangkar"
SE5 = "Ranggung"
STC = "Sengkang"
SW2 = "Farmway"
SW4 = "Thanggam"
SW5 = "Fernvale"
SW6 = "Layar"
SW7 = "Tongkang"
SW8 = "Renjong"

[segments]
BP1-BP2 = {duration = 2}
BP2-BP3 = {duration = 1}
BP3-BP4 = {duration = 2}
BP4-BP5 = {duration = 1}
BP5-BP6 = {duration = 1, edge_type = "bukit_panjang_main"}
BP6-BP7 = {duration = 1, edge_type = "bukit_panjang_service_b"}
BP6-BP13 = {duration = 2, edge_type = "bukit_panjang_service_a"}
BP6-BP14 = {duration = 1, edge_type = "bukit_panjang_service_c"}
BP7-BP8 = {duration = 2}
BP8-BP9 = {duration = 1}
BP9-BP10 = {duration = 2}
BP10-BP11 = {duration = 1}
BP11-BP12 = {duration = 1}
BP12-BP13 = {duration = 2}
CC12-CC13 = {duration = 2}
CC13-CC14 = {duration = 2}
CC14-CC15 = {duration = 2}
CC15-CC16 = {duration = 2}
CG-CG1 = {duration = 3}
CG1-CG2 = {duration = 4}
EW1-EW2 = {duration = 3}
EW2-EW3 = {duration = 3}
EW3-EW4 = {duration = 3}
EW4-EW5 = {duration = 3}
EW5-EW6 = {duration = 3}
EW6-EW7 = {duration = 3}
EW7-EW8 = {duration = 2}
EW8-EW9 = {duration = 2}
EW9-EW10 = {duration = 3}
EW10-EW11 = {duration = 2}
EW11-EW12 = {duration = 3}
EW12-EW13 = {duration = 2}
EW13-EW14 = {duration = 2}
EW14-EW15 = {duration = 2}
EW15-EW16 = {duration = 2}
EW16-EW17 = {duration = 3}
EW17-EW18 = {duration = 3}
EW18-EW19 = {duration = 2}
EW19-EW20 = {duration = 3}
EW20-EW21 = {duration = 2}
EW21-EW22 = {duration = 3}
EW22-EW23 = {duration = 2}
EW23-EW24 = {duration = 5}
EW24-EW25 = {duration = 2}
EW25-EW26 = {duration = 3}
EW26-EW27 = {duration = 2}
EW27-EW28 = {duration = 3}
EW28-EW29 = {duration = 3}
NE1-NE3 = {duration = 4}
NE3-NE4 = {duration = 1}
NE4-EW14 = {duration = 11, mode = "walk"}
NE4-NE5 = {duration = 2}
NE4-NS26 = {duration = 11, mode = "walk"}
NE5-EW14 = {duration = 10, mode = "walk"}
NE5-NE6 = {duration = 3}
NE5-NS26 = {duration = 10, mode = "walk"}
NE6-NE7 = {duration = 1}
NE7-NE8 = {duration = 1}
NE8-NE9 = {duration = 2}
NE9-NE10 = {duration = 3}
NE10-NE12 = {duration = 3}
NE12-NE13 = {duration = 3}
NE13-NE14 = {duration = 2}
NE14-NE15 = {duration = 2}
NE15-NE16 = {duration = 2}
NE16-NE17 = {duration = 3}
NS1-NS2 = {duration = 3}
NS2-NS3 = {duration = 3}
NS3-NS4 = {duration = 4}
NS4-NS5 = {duration = 2}
NS5-NS7 = {duration = 5}
NS7-NS8 = {duration = 3}
NS8-NS9 = {duration = 3}
NS9-NS10 = {duration = 3}
NS10-NS11 = {duration = 3}
NS11-NS13 = {duration = 5}
NS13-NS14 = {duration = 2}
NS14-NS15 = {duration = 5}
NS15-NS16 = {duration = 3}
NS16-NS17 = {duration = 4}
NS17-NS18 = {duration = 2}
NS18-NS19 = {duration = 2}
NS19-NS20 = {duration = 3}
NS20-NS21 = {duration = 2}
NS21-NS22 = {duration = 3}
NS22-NS23 = {duration = 2}
NS23-NS24 = {duration = 2}
NS24-NS25 = {duration = 3}
NS25-NS26 = {duration = 2}
NS26-NS27 = {duration = 2}
PE1-PE2 = {duration = 1}
PE2-PE3 = {duration = 1}
PE3-PE4 = {duration = 1}
PE4-PE5 = {duration = 1}
PE5-PE6 = {duration = 1}
PTC-PE1 = {duration = 3, edge_type = "punggol_east_loop"}
PTC-PE6 = {duration = 3, edge_type = "punggol_east_loop"}
SE1-SE2 = {duration = 1}
SE2-SE3 = {duration = 1}
SE3-SE4 = {duration = 1}
SE4-SE5 = {duration = 2}
STC-SE1 = {duration = 2, edge_type = "sengkang_east_loop"}
STC-SE5 = {duration = 3, edge_type = "sengkang_east_loop"}
STC-SW2 = {duration = 3, edge_type = "sengkang_west_loop"}
STC-SW8 = {duration = 3, edge_type = "sengkang_west_loop"}
SW2-SW4 = {duration = 2}
SW4-SW5 = {duration = 1}
SW5-SW6 = {duration = 1}
SW6-SW7 = {duration = 1}
SW7-SW8 = {duration = 1}

[transfers]
BP1-NS4 = {duration = 7}
CC13-NE12 = {duration = 8}
CC15-NS17 = {duration = 8}
CG-EW4 = {duration = 7}
EW4-CG = {duration = 7}
EW13-NS25 = {duration = 6}
EW14-NS26 = {duration = 6}
EW16-NE3 = {duration = 8}
EW24-NS1 = {duration = 7}
NE3-EW16 = {duration = 8}
NE6-NS24 = {duration = 8}
NE12-CC13 = {duration = 8}
NE16-STC = {duration = 7}
NE17-PTC = {duration = 7}
NS1-EW24 = {duration = 7}
NS4-BP1 = {duration = 7}
NS17-CC15 = {duration = 8}
NS24-NE6 = {duration = 8}
NS25-EW13 = {duration = 6}
NS26-EW14 = {duration = 6}
PTC-NE17 = {duration = 7}
STC-NE16 = {duration = 7}
