schema = 1
default_transfer_time = 420
default_dwell_time = 30

[stations]
EW1 = "Pasir Ris"
EW2 = "Tampines"
EW3 = "Simei"
EW4 = "Tanah Merah"
EW5 = "Bedok"
EW6 = "Kembangan"
EW7 = "Eunos"
EW8 = "Paya Lebar"
EW9 = "Aljunied"
EW10 = "Kallang"
EW11 = "Lavender"
EW12 = "Bugis"
EW13 = "City Hall"
EW14 = "Raffles Place"
EW15 = "Tanjong Pagar"
EW16 = "Outram Park"
EW17 = "Tiong Bahru"
EW18 = "Redhill"
EW19 = "Queenstown"
EW20 = "Commonwealth"
EW21 = "Buona Vista"
EW23 = "Clementi"
EW24 = "Jurong East"
EW25 = "Chinese Garden"
EW26 = "Lakeside"
NS1 = "Jurong East"
NS2 = "Bukit Batok"
NS3 = "Bukit Gombak"
NS4 = "Choa Chu Kang"
NS13 = "Yishun"
NS14 = "Khatib"
NS15 = "Yio Chu Kang"
NS16 = "Ang Mo Kio"
NS17 = "Bishan"
NS18 = "Braddell"
NS19 = "Toa Payoh"
NS20 = "Novena"
NS21 = "Newton"
NS22 = "Orchard"
NS23 = "Somerset"
NS24 = "Dhoby Ghaut"
NS25 = "City Hall"
NS26 = "Raffles Place"
NS27 = "Marina Bay"

[segments]
EW1-EW2 = {duration = 180}
EW2-EW3 = {duration = 180}
EW3-EW4 = {duration = 180}
EW4-EW5 = {duration = 180}
EW5-EW6 = {duration = 180}
EW6-EW7 = {duration = 180}
EW7-EW8 = {duration = 120}
EW8-EW9 = {duration = 120}
EW9-EW10 = {duration = 180}
EW10-EW11 = {duration = 120}
EW11-EW12 = {duration = 180}
EW12-EW13 = {duration = 120}
EW13-EW14 = {duration = 120}
EW14-EW15 = {duration = 120}
EW15-EW16 = {duration = 120}
EW16-EW17 = {duration = 180}
EW17-EW18 = {duration = 180}
EW18-EW19 = {duration = 120}
EW19-EW20 = {duration = 180}
EW20-EW21 = {duration = 120}
EW21-EW23 = {duration = 300}
EW23-EW24 = {duration = 300}
EW24-EW25 = {duration = 120}
EW25-EW26 = {duration = 180}
NS1-NS2 = {duration = 180}
NS2-NS3 = {duration = 180}
NS3-NS4 = {duration = 240}
NS13-NS14 = {duration = 120}
NS14-NS15 = {duration = 300}
NS15-NS16 = {duration = 180}
NS16-NS17 = {duration = 240}
NS17-NS18 = {duration = 120}
NS18-NS19 = {duration = 120}
NS19-NS20 = {duration = 180}
NS20-NS21 = {duration = 120}
NS21-NS22 = {duration = 180}
NS22-NS23 = {duration = 120}
NS23-NS24 = {duration = 120}
NS24-NS25 = {duration = 180}
NS25-NS26 = {duration = 120}
NS26-NS27 = {duration = 120}

[transfers]
EW13-NS25 = {duration = 360}
EW14-NS26 = {duration = 360}
EW24-NS1 = {duration = 420}
NS1-EW24 = {duration = 420}
NS25-EW13 = {duration = 360}
NS26-EW14 = {duration = 360}
