schema = 1
default_transfer_time = 7
default_dwell_time_asc = 0.5
default_dwell_time_desc = 0.5

[stations]
EW4 = "Tanah Merah"
EW5 = "Bedok"
EW6 = "Kembangan"
EW7 = "Eunos"
EW8 = "Paya Lebar"
EW9 = "Aljunied"
EW10 = "Kallang"
EW11 = "Lavender"
EW12 = "Bugis"
EW13 = "City Hall"
EW14 = "Raffles Place"
EW15 = "Tanjong Pagar"
EW16 = "Outram Park"
EW17 = "Tiong Bahru"
EW18 = "Redhill"
EW19 = "Queenstown"
EW20 = "Commonwealth"
EW21 = "Buona Vista"
EW23 = "Clementi"
EW24 = "Jurong East"
EW25 = "Chinese Garden"
EW26 = "Lakeside"
NS13 = "Yishun"
NS14 = "Khatib"
NS15 = "Yio Chu Kang"
NS16 = "Ang Mo Kio"
NS17 = "Bishan"
NS18 = "Braddell"
NS19 = "Toa Payoh"
NS20 = "Novena"
NS21 = "Newton"
NS22 = "Orchard"
NS23 = "Somerset"
NS24 = "Dhoby Ghaut"
NS25 = "City Hall"
NS26 = "Raffles Place"
NS27 = "Marina Bay"

[segments]
EW4-EW5 = {duration = 3}
EW5-EW6 = {duration = 3}
EW6-EW7 = {duration = 3}
EW7-EW8 = {duration = 2}
EW8-EW9 = {duration = 2}
EW9-EW10 = {duration = 3}
EW10-EW11 = {duration = 2}
EW11-EW12 = {duration = 3}
EW12-EW13 = {duration = 2}
EW13-EW14 = {duration = 2}
EW14-EW15 = {duration = 2}
EW15-EW16 = {duration = 2}
EW16-EW17 = {duration = 3}
EW17-EW18 = {duration = 3}
EW18-EW19 = {duration = 2}
EW19-EW20 = {duration = 3}
EW20-EW21 = {duration = 2}
EW21-EW23 = {duration = 5}
EW23-EW24 = {duration = 5}
EW24-EW25 = {duration = 2}
EW25-EW26 = {duration = 3}
NS13-NS14 = {duration = 2}
NS14-NS15 = {duration = 5}
NS15-NS16 = {duration = 3}
NS16-NS17 = {duration = 4}
NS17-NS18 = {duration = 2}
NS18-NS19 = {duration = 2}
NS19-NS20 = {duration = 3}
NS20-NS21 = {duration = 2}
NS21-NS22 = {duration = 3}
NS22-NS23 = {duration = 2}
NS23-NS24 = {duration = 2}
NS24-NS25 = {duration = 3}
NS25-NS26 = {duration = 2}
NS26-NS27 = {duration = 2}
