schema = 1
default_transfer_time = 420
default_dwell_time = 30

[stations]
BP1 = "Choa Chu Kang"
BP2 = "South View"
BP3 = "Keat Hong"
BP4 = "Teck Whye"
BP5 = "Phoenix"
BP6 = "Bukit Panjang"
BP7 = "Petir"
BP8 = "Pending"
BP9 = "Bangkit"
BP10 = "Fajar"
BP11 = "Segar"
BP12 = "Jelapang"
BP13 = "Senja"
BP14 = "Ten Mile Junction"
CG = "Tanah Merah"
CG1 = "Expo"
CG2 = "Changi Airport"
EW1 = "Pasir Ris"
EW2 = "Tampines"
EW3 = "Simei"
EW4 = "Tanah Merah"
EW5 = "Bedok"
EW6 = "Kembangan"
EW7 = "Eunos"
EW8 = "Paya Lebar"
EW9 = "Aljunied"
EW10 = "Kallang"
EW11 = "Lavender"
EW12 = "Bugis"
EW13 = "City Hall"
EW14 = "Raffles Place"
EW15 = "Tanjong Pagar"
EW16 = "Outram Park"
EW17 = "Tiong Bahru"
EW18 = "Redhill"
EW19 = "Queenstown"
EW20 = "Commonwealth"
EW21 = "Buona Vista"
EW22 = "Dover"
EW23 = "Clementi"
EW24 = "Jurong East"
EW25 = "Chinese Garden"
EW26 = "Lakeside"
EW27 = "Boon Lay"
NE1 = "HarbourFront"
NE3 = "Outram Park"
NE4 = "Chinatown"
NE5 = "Clarke Quay"
NE6 = "Dhoby Ghaut"
NE7 = "Little India"
NE8 = "Farrer Park"
NE9 = "Boon Keng"
NE10 = "Potong Pasir"
NE12 = "Serangoon"
NE13 = "Kovan"
NE14 = "Hougang"
NE16 = "Sengkang"
NE17 = "Punggol"
NS1 = "Jurong East"
NS2 = "Bukit Batok"
NS3 = "Bukit Gombak"
NS4 = "Choa Chu Kang"
NS5 = "Yew Tee"
NS7 = "Kranji"
NS8 = "Marsiling"
NS9 = "Woodlands"
NS10 = "Admiralty"
NS11 = "Sembawang"
NS13 = "Yishun"
NS14 = "Khatib"
NS15 = "Yio Chu Kang"
NS16 = "Ang Mo Kio"
NS17 = "Bishan"
NS18 = "Braddell"
NS19 = "Toa Payoh"
NS20 = "Novena"
NS21 = "Newton"
NS22 = "Orchard"
NS23 = "Somerset"
NS24 = "Dhoby Ghaut"
NS25 = "City Hall"
NS26 = "Raffles Place"
NS27 = "Marina Bay"
PE1 = "Cove"
PE2 = "Meridian"
PE3 = "Coral Edge"
PE4 = "Riviera"
PE5 = "Kadaloor"
PTC = "Punggol"
SE1 = "Compassvale"
SE2 = "Rumbia"
SE3 = "Bakau"
SE4 = "Kangkar"
SE5 = "Ranggung"
STC = "Sengkang"
SW4 = "Thanggam"
SW5 = "Fernvale"
SW6 = "Layar"
SW7 = "Tongkang"
SW8 = "Renjong"

[segments]
BP1-BP2 = {duration = 120}
BP2-BP3 = {duration = 60}
BP3-BP4 = {duration = 120}
BP4-BP5 = {duration = 60}
BP5-BP6 = {duration = 60, edge_type = "bukit_panjang_main"}
BP6-BP7 = {duration = 60, edge_type = "bukit_panjang_service_b"}
BP6-BP13 = {duration = 120, edge_type = "bukit_panjang_service_a"}
BP6-BP14 = {duration = 60, edge_type = "bukit_panjang_service_c"}
BP7-BP8 = {duration = 120}
BP8-BP9 = {duration = 60}
BP9-BP10 = {duration = 120}
BP10-BP11 = {duration = 60}
BP11-BP12 = {duration = 60}
BP12-BP13 = {duration = 120}
CG-CG1 = {duration = 180}
CG1-CG2 = {duration = 240}
EW1-EW2 = {duration = 180}
EW2-EW3 = {duration = 180}
EW3-EW4 = {duration = 180}
EW4-EW5 = {duration = 180}
EW5-EW6 = {duration = 180}
EW6-EW7 = {duration = 180}
EW7-EW8 = {duration = 120}
EW8-EW9 = {duration = 120}
EW9-EW10 = {duration = 180}
EW10-EW11 = {duration = 120}
EW11-EW12 = {duration = 180}
EW12-EW13 = {duration = 120}
EW13-EW14 = {duration = 120}
EW14-EW15 = {duration = 120}
EW15-EW16 = {duration = 120}
EW16-EW17 = {duration = 180}
EW17-EW18 = {duration = 180}
EW18-EW19 = {duration = 120}
EW19-EW20 = {duration = 180}
EW20-EW21 = {duration = 120}
EW21-EW22 = {duration = 180}
EW22-EW23 = {duration = 120}
EW23-EW24 = {duration = 300}
EW24-EW25 = {duration = 120}
EW25-EW26 = {duration = 180}
EW26-EW27 = {duration = 120}
NE1-NE3 = {duration = 240}
NE3-NE4 = {duration = 60}
NE4-EW14 = {duration = 660, mode = "walk"}
NE4-NE5 = {duration = 120}
NE4-NS26 = {duration = 660, mode = "walk"}
NE5-EW14 = {duration = 600, mode = "walk"}
NE5-NE6 = {duration = 180}
NE5-NS26 = {duration = 600, mode = "walk"}
NE6-NE7 = {duration = 60}
NE7-NE8 = {duration = 60}
NE8-NE9 = {duration = 120}
NE9-NE10 = {duration = 180}
NE10-NE12 = {duration = 180}
NE12-NE13 = {duration = 180}
NE13-NE14 = {duration = 120}
NE14-NE16 = {duration = 240}
NE16-NE17 = {duration = 180}
NS1-NS2 = {duration = 180}
NS2-NS3 = {duration = 180}
NS3-NS4 = {duration = 240}
NS4-NS5 = {duration = 120}
NS5-NS7 = {duration = 300}
NS7-NS8 = {duration = 180}
NS8-NS9 = {duration = 180}
NS9-NS10 = {duration = 180}
NS10-NS11 = {duration = 180}
NS11-NS13 = {duration = 300}
NS13-NS14 = {duration = 120}
NS14-NS15 = {duration = 300}
NS15-NS16 = {duration = 180}
NS16-NS17 = {duration = 240}
NS17-NS18 = {duration = 120}
NS18-NS19 = {duration = 120}
NS19-NS20 = {duration = 180}
NS20-NS21 = {duration = 120}
NS21-NS22 = {duration = 180}
NS22-NS23 = {duration = 120}
NS23-NS24 = {duration = 120}
NS24-NS25 = {duration = 180}
NS25-NS26 = {duration = 120}
NS26-NS27 = {duration = 120}
PE1-PE2 = {duration = 60}
PE2-PE3 = {duration = 60}
PE3-PE4 = {duration = 60}
PE4-PE5 = {duration = 60}
PTC-PE1 = {duration = 180, edge_type = "punggol_east_loop"}
PTC-PE5 = {duration = 240, edge_type = "punggol_east_loop"}
SE1-SE2 = {duration = 60}
SE2-SE3 = {duration = 60}
SE3-SE4 = {duration = 60}
SE4-SE5 = {duration = 120}
STC-SE1 = {duration = 120, edge_type = "sengkang_east_loop"}
STC-SE5 = {duration = 180, edge_type = "sengkang_east_loop"}
STC-SW4 = {duration = 300, edge_type = "sengkang_west_loop"}
STC-SW8 = {duration = 180, edge_type = "sengkang_west_loop"}
SW4-SW5 = {duration = 60}
SW5-SW6 = {duration = 60}
SW6-SW7 = {duration = 60}
SW7-SW8 = {duration = 60}

[transfers]
BP1-NS4 = {duration = 420}
CG-EW4 = {duration = 420}
EW4-CG = {duration = 420}
EW13-NS25 = {duration = 360}
EW14-NS26 = {duration = 360}
EW16-NE3 = {duration = 480}
EW24-NS1 = {duration = 420}
NE3-EW16 = {duration = 480}
NE6-NS24 = {duration = 480}
NE16-STC = {duration = 420}
NE17-PTC = {duration = 420}
NS1-EW24 = {duration = 420}
NS4-BP1 = {duration = 420}
NS24-NE6 = {duration = 480}
NS25-EW13 = {duration = 360}
NS26-EW14 = {duration = 360}
PTC-NE17 = {duration = 420}
STC-NE16 = {duration = 420}
