schema = 1

[stations]
EW15 = "Tanjong Pagar"
EW16 = "Outram Park"
EW17 = "Tiong Bahru"
EW18 = "Redhill"
EW19 = "Queenstown"
EW20 = "Commonwealth"
EW21 = "Buona Vista"
EW23 = "Clementi"
EW24 = "Jurong East"
EW25 = "Chinese Garden"
EW26 = "Lakeside"
NS15 = "Yio Chu Kang"
NS16 = "Ang Mo Kio"
NS17 = "Bishan"
NS18 = "Braddell"
NS19 = "Toa Payoh"
NS20 = "Novena"
NS21 = "Newton"
NS22 = "Orchard"
NS23 = "Somerset"
NS24 = "Dhoby Ghaut"
NS25 = "City Hall"
NS26 = "Raffles Place"

[segments]
EW15-EW16 = {duration_asc = 85, duration_desc = 85, dwell_time_asc = 28, dwell_time_desc = 28}
EW15-NS26 = {duration_asc = 105, duration_desc = 105, dwell_time_asc = 28, dwell_time_desc = 28}
EW16-EW17 = {duration_asc = 130, duration_desc = 130, dwell_time_asc = 28, dwell_time_desc = 28}
EW17-EW18 = {duration_asc = 105, duration_desc = 105, dwell_time_asc = 28, dwell_time_desc = 28}
EW18-EW19 = {duration_asc = 100, duration_desc = 100, dwell_time_asc = 28, dwell_time_desc = 28}
EW19-EW20 = {duration_asc = 90, duration_desc = 90, dwell_time_asc = 28, dwell_time_desc = 28}
EW20-EW21 = {duration_asc = 90, duration_desc = 90, dwell_time_asc = 28, dwell_time_desc = 28}
EW21-EW23 = {duration_asc = 300, duration_desc = 300, dwell_time_asc = 28, dwell_time_desc = 28}
EW23-EW24 = {duration_asc = 260, duration_desc = 260, dwell_time_asc = 28, dwell_time_desc = 28}
EW24-EW25 = {duration_asc = 105, duration_desc = 105, dwell_time_asc = 28, dwell_time_desc = 28}
EW25-EW26 = {duration_asc = 110, duration_desc = 110, dwell_time_asc = 28, dwell_time_desc = 60}
NS15-NS16 = {duration_asc = 115, duration_desc = 115, dwell_time_asc = 60, dwell_time_desc = 28}
NS16-NS17 = {duration_asc = 160, duration_desc = 160, dwell_time_asc = 28, dwell_time_desc = 28}
NS17-NS18 = {duration_asc = 95, duration_desc = 95, dwell_time_asc = 28, dwell_time_desc = 28}
NS18-NS19 = {duration_asc = 95, duration_desc = 95, dwell_time_asc = 28, dwell_time_desc = 28}
NS19-NS20 = {duration_asc = 110, duration_desc = 110, dwell_time_asc = 28, dwell_time_desc = 28}
NS20-NS21 = {duration_asc = 100, duration_desc = 100, dwell_time_asc = 28, dwell_time_desc = 28}
NS21-NS22 = {duration_asc = 110, duration_desc = 110, dwell_time_asc = 28, dwell_time_desc = 28}
NS22-NS23 = {duration_asc = 100, duration_desc = 100, dwell_time_asc = 28, dwell_time_desc = 28}
NS23-NS24 = {duration_asc = 75, duration_desc = 75, dwell_time_asc = 28, dwell_time_desc = 28}
NS24-NS25 = {duration_asc = 85, duration_desc = 85, dwell_time_asc = 28, dwell_time_desc = 28}
NS25-NS26 = {duration_asc = 100, duration_desc = 100, dwell_time_asc = 28, dwell_time_desc = 28}

[transfers]

[conditional_transfers]

[non_linear_line_terminals]
EW.EW26 = 1
EW.NS15 = 1
NS.EW26 = 1
NS.NS15 = 1

[station_code_pseudonyms]