schema = 1

[stations]
NS15 = "Yio Chu Kang"
NS16 = "Ang Mo Kio"
NS17 = "Bishan"
NS18 = "Braddell"
NS19 = "Toa Payoh"

[segments]
NS15-NS16 = {duration_asc = 115, duration_desc = 115, dwell_time_asc = 60, dwell_time_desc = 28}
NS16-NS17 = {duration_asc = 160, duration_desc = 160, dwell_time_asc = 28, dwell_time_desc = 28}
NS17-NS18 = {duration_asc = 95, duration_desc = 95, dwell_time_asc = 28, dwell_time_desc = 28}
NS18-NS19 = {duration_asc = 95, duration_desc = 95, dwell_time_asc = 28, dwell_time_desc = 60}

[transfers]

[conditional_transfers]

[non_linear_line_terminals]

[station_code_pseudonyms]
