schema = 1

[stations]
BP1 = "Choa Chu Kang"
BP2 = "South View"
BP3 = "Keat Hong"
BP4 = "Teck Whye"
BP5 = "Phoenix"
BP6 = "Bukit Panjang"
BP7 = "Petir"
BP8 = "Pending"
BP9 = "Bangkit"
BP10 = "Fajar"
BP11 = "Segar"
BP12 = "Jelapang"
BP13 = "Senja"
BP14 = "Ten Mile Junction"
CG = "Tanah Merah"
CG1 = "Expo"
CG2 = "Changi Airport"
EW1 = "Pasir Ris"
EW2 = "Tampines"
EW3 = "Simei"
EW4 = "Tanah Merah"
EW5 = "Bedok"
EW6 = "Kembangan"
EW7 = "Eunos"
EW8 = "Paya Lebar"
EW9 = "Aljunied"
EW10 = "Kallang"
EW11 = "Lavender"
EW12 = "Bugis"
EW13 = "City Hall"
EW14 = "Raffles Place"
EW15 = "Tanjong Pagar"
EW16 = "Outram Park"
EW17 = "Tiong Bahru"
EW18 = "Redhill"
EW19 = "Queenstown"
EW20 = "Commonwealth"
EW21 = "Buona Vista"
EW22 = "Dover"
EW23 = "Clementi"
EW24 = "Jurong East"
EW25 = "Chinese Garden"
EW26 = "Lakeside"
EW27 = "Boon Lay"
NE1 = "HarbourFront"
NE3 = "Outram Park"
NE4 = "Chinatown"
NE5 = "Clarke Quay"
NE6 = "Dhoby Ghaut"
NE7 = "Little India"
NE8 = "Farrer Park"
NE9 = "Boon Keng"
NE10 = "Potong Pasir"
NE12 = "Serangoon"
NE13 = "Kovan"
NE14 = "Hougang"
NE16 = "Sengkang"
NE17 = "Punggol"
NS1 = "Jurong East"
NS2 = "Bukit Batok"
NS3 = "Bukit Gombak"
NS4 = "Choa Chu Kang"
NS5 = "Yew Tee"
NS7 = "Kranji"
NS8 = "Marsiling"
NS9 = "Woodlands"
NS10 = "Admiralty"
NS11 = "Sembawang"
NS13 = "Yishun"
NS14 = "Khatib"
NS15 = "Yio Chu Kang"
NS16 = "Ang Mo Kio"
NS17 = "Bishan"
NS18 = "Braddell"
NS19 = "Toa Payoh"
NS20 = "Novena"
NS21 = "Newton"
NS22 = "Orchard"
NS23 = "Somerset"
NS24 = "Dhoby Ghaut"
NS25 = "City Hall"
NS26 = "Raffles Place"
NS27 = "Marina Bay"
PE1 = "Cove"
PE2 = "Meridian"
PE3 = "Coral Edge"
PE4 = "Riviera"
PE5 = "Kadaloor"
PTC = "Punggol"
SE1 = "Compassvale"
SE2 = "Rumbia"
SE3 = "Bakau"
SE4 = "Kangkar"
SE5 = "Ranggung"
STC = "Sengkang"
SW4 = "Thanggam"
SW5 = "Fernvale"
SW6 = "Layar"
SW7 = "Tongkang"
SW8 = "Renjong"

[segments]
BP1-BP2 = {duration_asc = 85, duration_desc = 85, dwell_time_asc = 60, dwell_time_desc = 28}
BP2-BP3 = {duration_asc = 50, duration_desc = 50, dwell_time_asc = 28, dwell_time_desc = 28}
BP3-BP4 = {duration_asc = 60, duration_desc = 60, dwell_time_asc = 28, dwell_time_desc = 28}
BP4-BP5 = {duration_asc = 60, duration_desc = 60, dwell_time_asc = 28, dwell_time_desc = 28}
BP5-BP6 = {duration_asc = 90, duration_desc = 90, edge_type = "bukit_panjang_main", dwell_time_asc = 28, dwell_time_desc = 45}
BP6-BP7 = {duration_asc = 60, duration_desc = 60, edge_type = "bukit_panjang_service_b", dwell_time_asc = 45, dwell_time_desc = 28}
BP6-BP13 = {duration_asc = 70, duration_desc = 70, edge_type = "bukit_panjang_service_a", dwell_time_asc = 45, dwell_time_desc = 28}
BP6-BP14 = {duration_asc = 120, duration_desc = 120, edge_type = "bukit_panjang_service_c", dwell_time_asc = 45, dwell_time_desc = 28}
BP7-BP8 = {duration_asc = 85, duration_desc = 85, dwell_time_asc = 28, dwell_time_desc = 28}
BP8-BP9 = {duration_asc = 60, duration_desc = 60, dwell_time_asc = 28, dwell_time_desc = 28}
BP9-BP10 = {duration_asc = 105, duration_desc = 105, dwell_time_asc = 28, dwell_time_desc = 28}
BP10-BP11 = {duration_asc = 60, duration_desc = 60, dwell_time_asc = 28, dwell_time_desc = 28}
BP11-BP12 = {duration_asc = 80, duration_desc = 80, dwell_time_asc = 28, dwell_time_desc = 28}
BP12-BP13 = {duration_asc = 60, duration_desc = 60, dwell_time_asc = 28, dwell_time_desc = 28}
CG-CG1 = {duration_asc = 135, duration_desc = 135, dwell_time_asc = 60, dwell_time_desc = 28}
CG1-CG2 = {duration_asc = 255, duration_desc = 255, dwell_time_asc = 28, dwell_time_desc = 60}
EW1-EW2 = {duration_asc = 150, duration_desc = 150, dwell_time_asc = 60, dwell_time_desc = 28}
EW2-EW3 = {duration_asc = 105, duration_desc = 105, dwell_time_asc = 28, dwell_time_desc = 28}
EW3-EW4 = {duration_asc = 150, duration_desc = 150, dwell_time_asc = 28, dwell_time_desc = 45}
EW4-EW5 = {duration_asc = 125, duration_desc = 125, dwell_time_asc = 45, dwell_time_desc = 28}
EW5-EW6 = {duration_asc = 140, duration_desc = 140, dwell_time_asc = 28, dwell_time_desc = 28}
EW6-EW7 = {duration_asc = 85, duration_desc = 85, dwell_time_asc = 28, dwell_time_desc = 28}
EW7-EW8 = {duration_asc = 85, duration_desc = 85, dwell_time_asc = 28, dwell_time_desc = 28}
EW8-EW9 = {duration_asc = 95, duration_desc = 95, dwell_time_asc = 28, dwell_time_desc = 28}
EW9-EW10 = {duration_asc = 100, duration_desc = 100, dwell_time_asc = 28, dwell_time_desc = 28}
EW10-EW11 = {duration_asc = 85, duration_desc = 85, dwell_time_asc = 28, dwell_time_desc = 28}
EW11-EW12 = {duration_asc = 85, duration_desc = 85, dwell_time_asc = 28, dwell_time_desc = 28}
EW12-EW13 = {duration_asc = 85, duration_desc = 85, dwell_time_asc = 28, dwell_time_desc = 45}
EW13-EW14 = {duration_asc = 90, duration_desc = 90, dwell_time_asc = 45, dwell_time_desc = 45}
EW14-EW15 = {duration_asc = 105, duration_desc = 105, dwell_time_asc = 45, dwell_time_desc = 28}
EW15-EW16 = {duration_asc = 85, duration_desc = 85, dwell_time_asc = 28, dwell_time_desc = 45}
EW16-EW17 = {duration_asc = 130, duration_desc = 130, dwell_time_asc = 45, dwell_time_desc = 28}
EW17-EW18 = {duration_asc = 105, duration_desc = 105, dwell_time_asc = 28, dwell_time_desc = 28}
EW18-EW19 = {duration_asc = 100, duration_desc = 100, dwell_time_asc = 28, dwell_time_desc = 28}
EW19-EW20 = {duration_asc = 90, duration_desc = 90, dwell_time_asc = 28, dwell_time_desc = 28}
EW20-EW21 = {duration_asc = 90, duration_desc = 90, dwell_time_asc = 28, dwell_time_desc = 28}
EW21-EW22 = {duration_asc = 105, duration_desc = 105, dwell_time_asc = 28, dwell_time_desc = 28}
EW22-EW23 = {duration_asc = 120, duration_desc = 120, dwell_time_asc = 28, dwell_time_desc = 28}
EW23-EW24 = {duration_asc = 260, duration_desc = 260, dwell_time_asc = 28, dwell_time_desc = 45}
EW24-EW25 = {duration_asc = 105, duration_desc = 105, dwell_time_asc = 45, dwell_time_desc = 28}
EW25-EW26 = {duration_asc = 110, duration_desc = 110, dwell_time_asc = 28, dwell_time_desc = 28}
EW26-EW27 = {duration_asc = 145, duration_desc = 145, dwell_time_asc = 28, dwell_time_desc = 60}
NE1-NE3 = {duration_asc = 170, duration_desc = 170, dwell_time_asc = 60, dwell_time_desc = 45}
NE3-NE4 = {duration_asc = 75, duration_desc = 75, dwell_time_asc = 45, dwell_time_desc = 28}
NE4-EW14 = {duration_asc = 660, duration_desc = 660, mode = "walk", dwell_time_asc = 0, dwell_time_desc = 0}
NE4-NE5 = {duration_asc = 70, duration_desc = 70, dwell_time_asc = 28, dwell_time_desc = 28}
NE4-NS26 = {duration_asc = 660, duration_desc = 660, mode = "walk", dwell_time_asc = 0, dwell_time_desc = 0}
NE5-EW14 = {duration_asc = 600, duration_desc = 600, mode = "walk", dwell_time_asc = 0, dwell_time_desc = 0}
NE5-NE6 = {duration_asc = 115, duration_desc = 115, dwell_time_asc = 28, dwell_time_desc = 45}
NE5-NS26 = {duration_asc = 600, duration_desc = 600, mode = "walk", dwell_time_asc = 0, dwell_time_desc = 0}
NE6-NE7 = {duration_asc = 90, duration_desc = 90, dwell_time_asc = 45, dwell_time_desc = 28}
NE7-NE8 = {duration_asc = 80, duration_desc = 80, dwell_time_asc = 28, dwell_time_desc = 28}
NE8-NE9 = {duration_asc = 95, duration_desc = 95, dwell_time_asc = 28, dwell_time_desc = 28}
NE9-NE10 = {duration_asc = 125, duration_desc = 125, dwell_time_asc = 28, dwell_time_desc = 28}
NE10-NE12 = {duration_asc = 190, duration_desc = 190, dwell_time_asc = 28, dwell_time_desc = 28}
NE12-NE13 = {duration_asc = 130, duration_desc = 130, dwell_time_asc = 28, dwell_time_desc = 28}
NE13-NE14 = {duration_asc = 120, duration_desc = 120, dwell_time_asc = 28, dwell_time_desc = 28}
NE14-NE16 = {duration_asc = 215, duration_desc = 215, dwell_time_asc = 28, dwell_time_desc = 45}
NE16-NE17 = {duration_asc = 130, duration_desc = 130, dwell_time_asc = 45, dwell_time_desc = 60}
NS1-NS2 = {duration_asc = 225, duration_desc = 225, dwell_time_asc = 60, dwell_time_desc = 28}
NS2-NS3 = {duration_asc = 95, duration_desc = 95, dwell_time_asc = 28, dwell_time_desc = 28}
NS3-NS4 = {duration_asc = 205, duration_desc = 205, dwell_time_asc = 28, dwell_time_desc = 45}
NS4-NS5 = {duration_asc = 120, duration_desc = 120, dwell_time_asc = 45, dwell_time_desc = 28}
NS5-NS7 = {duration_asc = 250, duration_desc = 250, dwell_time_asc = 28, dwell_time_desc = 28}
NS7-NS8 = {duration_asc = 125, duration_desc = 125, dwell_time_asc = 28, dwell_time_desc = 28}
NS8-NS9 = {duration_asc = 125, duration_desc = 125, dwell_time_asc = 28, dwell_time_desc = 28}
NS9-NS10 = {duration_asc = 135, duration_desc = 135, dwell_time_asc = 28, dwell_time_desc = 28}
NS10-NS11 = {duration_asc = 150, duration_desc = 150, dwell_time_asc = 28, dwell_time_desc = 28}
NS11-NS13 = {duration_asc = 240, duration_desc = 240, dwell_time_asc = 28, dwell_time_desc = 28}
NS13-NS14 = {duration_asc = 105, duration_desc = 105, dwell_time_asc = 28, dwell_time_desc = 28}
NS14-NS15 = {duration_asc = 300, duration_desc = 300, dwell_time_asc = 28, dwell_time_desc = 28}
NS15-NS16 = {duration_asc = 115, duration_desc = 115, dwell_time_asc = 28, dwell_time_desc = 28}
NS16-NS17 = {duration_asc = 160, duration_desc = 160, dwell_time_asc = 28, dwell_time_desc = 28}
NS17-NS18 = {duration_asc = 95, duration_desc = 95, dwell_time_asc = 28, dwell_time_desc = 28}
NS18-NS19 = {duration_asc = 95, duration_desc = 95, dwell_time_asc = 28, dwell_time_desc = 28}
NS19-NS20 = {duration_asc = 110, duration_desc = 110, dwell_time_asc = 28, dwell_time_desc = 28}
NS20-NS21 = {duration_asc = 100, duration_desc = 100, dwell_time_asc = 28, dwell_time_desc = 28}
NS21-NS22 = {duration_asc = 110, duration_desc = 110, dwell_time_asc = 28, dwell_time_desc = 28}
NS22-NS23 = {duration_asc = 100, duration_desc = 100, dwell_time_asc = 28, dwell_time_desc = 28}
NS23-NS24 = {duration_asc = 75, duration_desc = 75, dwell_time_asc = 28, dwell_time_desc = 45}
NS24-NS25 = {duration_asc = 85, duration_desc = 85, dwell_time_asc = 45, dwell_time_desc = 45}
NS25-NS26 = {duration_asc = 100, duration_desc = 100, dwell_time_asc = 45, dwell_time_desc = 45}
NS26-NS27 = {duration_asc = 90, duration_desc = 90, dwell_time_asc = 45, dwell_time_desc = 60}
PE1-PE2 = {duration_asc = 55, duration_desc = 55, dwell_time_asc = 28, dwell_time_desc = 28}
PE2-PE3 = {duration_asc = 60, duration_desc = 60, dwell_time_asc = 28, dwell_time_desc = 28}
PE3-PE4 = {duration_asc = 60, duration_desc = 60, dwell_time_asc = 28, dwell_time_desc = 28}
PE4-PE5 = {duration_asc = 75, duration_desc = 75, dwell_time_asc = 28, dwell_time_desc = 28}
PTC-PE1 = {duration_asc = 120, duration_desc = 120, edge_type = "punggol_east_loop", dwell_time_asc = 28, dwell_time_desc = 45}
PTC-PE5 = {duration_asc = 210, duration_desc = 210, edge_type = "punggol_east_loop", dwell_time_asc = 28, dwell_time_desc = 45}
SE1-SE2 = {duration_asc = 75, duration_desc = 75, dwell_time_asc = 28, dwell_time_desc = 28}
SE2-SE3 = {duration_asc = 55, duration_desc = 55, dwell_time_asc = 28, dwell_time_desc = 28}
SE3-SE4 = {duration_asc = 70, duration_desc = 70, dwell_time_asc = 28, dwell_time_desc = 28}
SE4-SE5 = {duration_asc = 90, duration_desc = 90, dwell_time_asc = 28, dwell_time_desc = 28}
STC-SE1 = {duration_asc = 100, duration_desc = 100, edge_type = "sengkang_east_loop", dwell_time_asc = 28, dwell_time_desc = 45}
STC-SE5 = {duration_asc = 150, duration_desc = 150, edge_type = "sengkang_east_loop", dwell_time_asc = 28, dwell_time_desc = 45}
STC-SW4 = {duration_asc = 355, duration_desc = 355, edge_type = "sengkang_west_loop", dwell_time_asc = 45, dwell_time_desc = 28}
STC-SW8 = {duration_asc = 155, duration_desc = 155, edge_type = "sengkang_west_loop", dwell_time_asc = 45, dwell_time_desc = 28}
SW4-SW5 = {duration_asc = 75, duration_desc = 75, dwell_time_asc = 28, dwell_time_desc = 28}
SW5-SW6 = {duration_asc = 65, duration_desc = 65, dwell_time_asc = 28, dwell_time_desc = 28}
SW6-SW7 = {duration_asc = 70, duration_desc = 70, dwell_time_asc = 28, dwell_time_desc = 28}
SW7-SW8 = {duration_asc = 65, duration_desc = 65, dwell_time_asc = 28, dwell_time_desc = 28}

[transfers]
BP1-NS4 = {duration = 420}
CG-EW4 = {duration = 420}
EW4-CG = {duration = 420}
EW13-NS25 = {duration = 360}
EW14-NS26 = {duration = 360}
EW16-NE3 = {duration = 480}
EW24-NS1 = {duration = 420}
NE3-EW16 = {duration = 480}
NE6-NS24 = {duration = 480}
NE16-STC = {duration = 420}
NE17-PTC = {duration = 420}
NS1-EW24 = {duration = 420}
NS4-BP1 = {duration = 420}
NS24-NE6 = {duration = 480}
NS25-EW13 = {duration = 360}
NS26-EW14 = {duration = 360}
PTC-NE17 = {duration = 420}
STC-NE16 = {duration = 420}

[conditional_transfers]
bukit_panjang_main.bukit_panjang_service_c = 420
bukit_panjang_service_a.bukit_panjang_service_b = 420
bukit_panjang_service_a.bukit_panjang_service_c = 420
bukit_panjang_service_b.bukit_panjang_service_a = 420
bukit_panjang_service_b.bukit_panjang_service_c = 420
bukit_panjang_service_c.bukit_panjang_main = 420
bukit_panjang_service_c.bukit_panjang_service_a = 420
bukit_panjang_service_c.bukit_panjang_service_b = 420
sengkang_east_loop.sengkang_west_loop = 360
sengkang_west_loop.sengkang_east_loop = 360

[non_linear_line_terminals]
BP.BP1 = 1
BP.BP14 = 1
PE.PTC = 1
PTC.PTC = 1
SE.STC = 1
STC.STC = 1
SW.STC = 1

[station_code_pseudonyms]
