name: ci

on: [push, pull_request, workflow_dispatch]
jobs:
    format-markdown:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo content
              uses: actions/checkout@v4

            - name: Markdown format check
              run: |
                  npm install -g markdownlint-cli
                  markdownlint --disable MD013 MD033 MD041 --fix . --ignore CODE_OF_CONDUCT.md
                  git add -A
                  git diff --cached --exit-code
    test-and-coverage:
        strategy:
          matrix:
            os: [macos-latest, windows-latest, ubuntu-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: checkout repo content
              uses: actions/checkout@v4

            - uses: actions/setup-python@v5
              with:
                python-version: '3.x'

            - name: Install poetry
              run: |
                  pipx install poetry

            - name: Check lock file consistency
              run: |
                  poetry check --lock

            - name: Install dependencies
              run: |
                  make install

            - name: Ruff format check
              run: |
                  make ruff_format_check

            - name: Ruff lint check
              run: |
                  make ruff_check

            - name: Test
              run: |
                  poetry run pytest -vv --cov=./ --cov-report html
